site_name: 'Le YouTube de demain est-il libre ?'
site_description: 'Le YouTube de demain est-il libre ? Google continuera-t-il de dicter l'avenir des créateurs ? - Livre blanc sur le partage de vidéo'
site_author: Raphaël Cerveaux
site_url: https://sundowndev.github.io/livre-blanc-video/

# Repository
# repo_name: sundowndev/livre-blanc-video
# repo_url: https://github.com/sundowndev/livre-blanc-video
# edit_uri: 'https://github.com/sundowndev/livre-blanc-video/edit/master/docs/'

# Copyright
# copyright: 'Copyright &copy; 2019 Raphaël Cerveaux'

theme:
  name: 'material'
  include_sidebar: false
  palette:
    primary: teal
    accent: teal
  font:
    text: Nunito
    code: Roboto Mono
  plugins:
    - search
    - minify:
        minify_html: true

# Page tree
nav:
  - 'Introduction': index.md
  - "Le partage de contenu aujourd'hui": video-sharing-today.md
  - 'Modèle économique': business-model.md
  - 'En communauté': as-community.md
  - 'Opportunités': oportinities.md
